name: flutter_chatbot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  floor: ^1.5.0
  flutter:
    sdk: flutter
  markdown_widget: ^2.3.2+8
  font_awesome_flutter: ^10.7.0
  google_generative_ai: ^0.4.7
  path_provider: ^2.1.5
  skeletonizer: ^2.0.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.11
  floor_generator: ^1.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
